slacker/slacker/urls.py
from django.contrib import admin
from django.urls import path, include
from backend.views import rooms

urlpatterns = [
    path('', rooms.index, name='rooms-index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('rooms/', include('backend.urls.rooms')),
    path('guests/', include('backend.urls.guests')),
    path('accommodations/', include('backend.urls.accommodation')),
    path('reports/', include('backend.urls.report')),
    path('bookings/', include('backend.urls.booking')),
]

slacker/backend/models.py
from datetime import date

from django.conf import settings
from django.db import models
from django.utils import timezone


class Room(models.Model):

    EMPTY = 'EPT'
    OCCUPIED = 'OCP'
    CLEANING = 'CLN'
    REPAIR = 'RPR'

    STATUS_CHOICES = (
        (EMPTY, 'Пусто'),
        (OCCUPIED, 'Занято'),
        (CLEANING, 'Уборка'),
        (REPAIR, 'Ремонт'),
    )

    name = models.CharField(
        max_length=6,
        unique=True,
    )

    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default=EMPTY,
    )

    status_changed_at = models.DateTimeField()

    daily_price = models.FloatField()

    @property
    def daily_price_two_persons(self):
        return self.daily_price + 190

    @property
    def daily_price_three_persons(self):
        return self.daily_price + 190*2

    hourly_price = models.FloatField(
        null=True,
        blank=True,
    )

    @property
    def hourly_price_three_persons(self):
        if self.hourly_price:
            return self.hourly_price + 50

    bedding_configuration = models.ForeignKey(
        'BeddingConfiguration',
        on_delete=models.PROTECT
    )

    room_type = models.ForeignKey(
        'RoomType',
        on_delete=models.PROTECT,
    )

    current_accommodation = models.ForeignKey(
        'Accommodation',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='current_accommodation'
    )

    def __str__(self):
        return "%s (%s)" % (self.name, self.room_type)


class RoomType(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
    )

    def __str__(self):
        return self.name


class BeddingConfiguration(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
    )
    capacity = models.PositiveSmallIntegerField(
        default=1,
    )

    def __str__(self):
        return self.name


class RoomNote(models.Model):
    content = models.TextField(
        max_length=1000,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )
    room = models.ForeignKey(
        'Room',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "%s (%s)" % (self.room, self.created_at)


class Guest(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'

    SEX_CHOICES = (
        (MALE, 'муж.'),
        (FEMALE, 'жен.'),
        (OTHER, 'прочий')
    )

    last_name = models.CharField(
        max_length=50,
    )

    first_name = models.CharField(
        max_length=50,
    )

    patronymic = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )

    @property
    def fullname(self):
        if self.patronymic:
            return "%s %s %s" % (self.last_name, self.first_name, self.patronymic)
        else:
            return "%s %s" % (self.last_name, self.first_name)

    date_of_birth = models.DateField()

    @property
    def age(self):
        age = 0
        if self.date_of_birth:
            today = date.today()
            born = self.date_of_birth
            age = today.year - born.year - \
                ((today.month, today.day) < (born.month, born.day))
        return age

    place_of_birth = models.CharField(
        max_length=100,
    )

    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        default=MALE
    )

    citizenship = models.CharField(
        max_length=50
    )

    document_type = models.ForeignKey(
        'DocumentType',
        on_delete=models.PROTECT,
    )

    document_number = models.CharField(
        max_length=50
    )

    document_issued_by = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )

    document_issued_on = models.DateField(
        null=True,
        blank=True,
    )

    home_address = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )

    phone = models.CharField(
        max_length=20,
        null=True,
        blank=True,
    )

    email = models.EmailField(
        null=True,
        blank=True,
    )

    first_visit = models.DateField(
        auto_now_add=True
    )

    last_visit = models.DateField(
        null=True
    )

    personal_card_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )

    personal_discount = models.FloatField(
        blank=True,
        null=True,
    )

    note = models.CharField(
        max_length=300,
        null=True,
        blank=True
    )

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('guests-detail', args=[str(self.pk)])

    def __str__(self):
        return self.fullname


class DocumentType(models.Model):
    name = models.CharField(
        max_length=70,
        unique=True,
    )

    def __str__(self):
        return self.name


class AccommodationQuerySet(models.QuerySet):
    def recent_by_room(self, room):
        return self.filter(room_id=room.id).order_by('-id')[:50]

class Accommodation(models.Model):
    HOURLY = 'H'
    DAILY = 'D'

    ACCOMMODATION_CHOICES = (
        (HOURLY, 'Почасовая'),
        (DAILY, 'Дневная')
    )
    accommodation_quantity = models.FloatField()
    check_in = models.DateTimeField(
        default=timezone.now
    )
    check_out = models.DateTimeField(
        null=True,
        blank=True,
    )
    room = models.ForeignKey(
        'Room',
        on_delete=models.SET_NULL,
        null=True,
    )
    cost = models.FloatField(
        null=True,
        blank=True,
    )
    accommodation_type = models.CharField(
        max_length=1,
        choices=ACCOMMODATION_CHOICES,
        default=DAILY
    )
    guests = models.ManyToManyField(
        'Guest'
    )
    note = models.CharField(
        max_length=300,
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('accommodation-detail', args=[str(self.pk)])


class Booking(models.Model):
    NOT_CONFIRMED = 'NC'
    CONFIRMED = 'CO'
    CANCELED = 'CN'
    NO_SHOW = 'NS'
    CHECKED_IN = 'CI'

    STATUS_CHOICES = (
        (NOT_CONFIRMED, 'Непотверждено'),
        (CONFIRMED, 'Подтверждено'),
        (CANCELED, 'Отменено'),
        (NO_SHOW, 'Не прибытие'),
        (CHECKED_IN, 'Заселен')
    )

    source = models.ForeignKey(
        'BookingSource',
        on_delete=models.SET_NULL,
        null=True
    )
    number = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )
    room_type = models.ForeignKey(
        'RoomType',
        on_delete=models.SET_NULL,
        null=True,
    )
    number_of_guests = models.PositiveSmallIntegerField()
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default=NOT_CONFIRMED
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest_name = models.CharField(
        max_length=100
    )
    price = models.FloatField(
        blank=True,
        null=True
    )
    note = models.CharField(
        max_length=300,
        null=True,
        blank=True
    )

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('booking-edit', args=[str(self.pk)])


class BookingSource(models.Model):
    name = models.CharField(
        max_length=70,
        unique=True,
    )

    def __str__(self):
        return self.name


class Payment(models.Model):
    CASH = 'CASH'
    BANK_TRANSFER = 'BANK'
    POS = 'POS'

    PAYMENT_CHOICES = (
        (CASH, 'Наличные'),
        (BANK_TRANSFER, 'Банковский перевод'),
        (POS, 'Оплата картой')
    )

    payment_type = models.CharField(
        max_length=4,
        choices=PAYMENT_CHOICES,
        default=CASH,
    )

    accommodation = models.ForeignKey(
        'Accommodation',
        on_delete=models.SET_NULL,
        null=True,
    )
    amount = models.FloatField()
    made_on = models.DateTimeField(
        auto_now_add=True
    )

slacker/backend/forms/room.py
from django.forms import ModelForm, TextInput, EmailInput, TimeInput, DateInput, Textarea, Select
from backend.models import Room


class StatusForm(ModelForm):
    class Meta:
        model = Room
        fields = ['status']
        widgets = {
            'status': Select(attrs={'class': 'select'}),
        }

slacker/backend/views/accommodation.py
from django.core.paginator import Paginator
from django.db.models import Q, Sum
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from backend.models import Accommodation, Guest, Payment, Room
from backend.services.accommodation import *


def index(request):

    number_of_rows_on_a_page = 10
    accommodations = get_paginated_accommodations(request, number_of_rows_on_a_page)

    context = { 'accommodations': accommodations }

    return render(request, 'accommodation/index.html', context)



def create(request):

    room = get_room_or_404(request)

    context = { 'room': room }

    return render(request, 'accommodation/create.html', context)



@require_POST
def check_in(request):

    room = get_room_or_404(request)
    accommodation = create_accommodation(request, room)

    process_payment(request, accommodation)
    add_new_guests_to_accommodation(request, accommodation)
    set_room_occupied(room, accommodation)

    redirect_url = request.POST.get('next', '')

    return HttpResponseRedirect(redirect_url)



def check_out(request, accommodation_id):

    accommodation = get_object_or_404(Accommodation, pk=accommodation_id)
    accommodation.check_out = timezone.now()
    accommodation.save()

    set_room_vacant(accommodation)

    return HttpResponseRedirect('/')



def detail(request, accommodation_id):

    accommodation = get_object_or_404(Accommodation, pk=accommodation_id)
    room = get_object_or_404(Room, pk=accommodation.room.id)
    guests = accommodation.guests.all()
    payments = Payment.objects.filter(accommodation=accommodation)
    total_paid = sum(payment.amount for payment in payments)

    context = { 'accommodation': accommodation, 'room': room,
               'guests': guests, 'payments': payments, 'total_paid': total_paid }

    return render(request, 'accommodation/detail.html', context)



def new_payment(request, accommodation_id):

    redirect = request.GET.get('next', '')

    accommodation = get_object_or_404(Accommodation, pk=accommodation_id)

    process_payment(request, accommodation)

    return HttpResponseRedirect(redirect)



def update_note(request, accommodation_id):

    redirect = request.GET.get('next', '')

    accommodation = get_object_or_404(Accommodation, pk=accommodation_id)
    accommodation.note = request.POST['note']
    accommodation.save()

    return HttpResponseRedirect(redirect)

slacker/backend/views/booking.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from backend.forms.booking import BookingForm
from backend.models import Booking


def index(request):
    booking_list = Booking.objects.exclude(status = Booking.CHECKED_IN).order_by('check_in')
    paginator = Paginator(booking_list, 20)
    page = request.GET.get('page')
    bookings = paginator.get_page(page)
    context = {'bookings': bookings}
    return render(request, 'booking/index.html', context)

class BookingCreateView(SuccessMessageMixin, CreateView):
    model = Booking
    form_class = BookingForm
    template_name = 'booking/create.html'
    context_object_name = "booking"
    success_message = "Успешно создано!"

class BookingUpdateView(SuccessMessageMixin, UpdateView):
    model = Booking
    form_class = BookingForm
    template_name = 'booking/edit.html'
    context_object_name = "booking"
    success_message = "Успешно сохранено!"

slacker/backend/views/guests.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.views.generic.edit import CreateView, UpdateView

from backend.forms.guests import GuestForm
from backend.forms.room import StatusForm
from backend.models import Guest, Room, RoomNote, RoomType, Accommodation


def search(request):
    query = request.GET.get('query', '')
    guest_list = Guest.objects.filter(
        Q(last_name__icontains=query) | Q(document_number__contains=query) | Q(phone__contains=query)).order_by('-id')
    paginator = Paginator(guest_list, 15)
    page = request.GET.get('page')
    guests = paginator.get_page(page)
    context = {'guests': guests}

    return render(request, 'guests/search.html', context)


def detail(request, guest_id):
    guest = get_object_or_404(Guest, pk=guest_id)
    recent_accommodations = Accommodation.objects.filter(guests__id=guest.id).order_by('-id')[:50]
    context = {'guest': guest, 'recent_accommodations': recent_accommodations}

    return render(request, 'guests/detail.html', context)


class GuestCreateView(SuccessMessageMixin, CreateView):
    model = Guest
    form_class = GuestForm
    template_name = 'guests/create.html'
    context_object_name = "guest"
    success_message = "Успешно создано!"


class GuestUpdateView(SuccessMessageMixin, UpdateView):
    model = Guest
    form_class = GuestForm
    template_name = 'guests/update.html'
    context_object_name = "guest"
    success_message = "Успешно сохранено!"


def guests_autocomplete(request):
    query = request.GET.get('term', '')
    guests = Guest.objects.filter(
        Q(last_name__icontains=query) | Q(phone__contains=query) | Q(document_number__contains=query)).order_by('-id')[:10]
    results = []
    
    for guest in guests:
        guest_json = {}
        guest_json['id'] = guest.id
        guest_json['value'] = guest.fullname
        guest_json['label'] = "%s (%s)" % (guest.fullname, guest.document_number)
        guest_json['discount'] = guest.personal_discount
        results.append(guest_json)

    return JsonResponse(results, safe=False)

slacker/backend/views/report.py
from django.shortcuts import render, get_object_or_404, reverse, HttpResponseRedirect
from django.views.decorators.http import require_POST
from backend.models import Guest, Accommodation, Payment
from backend.forms.room import StatusForm
from django.utils import timezone
from django.contrib import messages
from datetime import datetime

# Create your views here.


def get_guest_blank(request):
    guest_id = request.GET['guest_id']
    accommodation_id = request.GET['accommodation_id']

    guest = get_object_or_404(Guest, pk=guest_id)
    accommodation = get_object_or_404(Accommodation, pk=accommodation_id)

    context = {'guest': guest, 'accommodation': accommodation}
    return render(request, 'report/guest_blank.html', context)


def shift_report_index(request):
    if request.GET.get('date'):
        period = request.GET.get('date')
        dates = period.split(' - ')
        datetimes = []

        for date in dates:
            date = datetime.strptime(date + ' 8:00:00', '%Y-%m-%d %H:%M:%S')
            datetimes.append(date)
            print(date)

        payments = Payment.objects.filter(made_on__range=datetimes).order_by(
            'accommodation__room__id', 'accommodation')

        cash_sum = 0
        pos_sum = 0
        bank_sum = 0

        for payment in payments:
            if payment.payment_type == Payment.CASH:
                cash_sum += payment.amount
            elif payment.payment_type == Payment.POS:
                pos_sum += payment.amount
            elif payment.payment_type == Payment.BANK_TRANSFER:
                bank_sum += payment.amount

        sum = {'cash': cash_sum, 'pos': pos_sum, 'bank': bank_sum}

        context = {'payments': payments, 'start': datetimes[0], 'end': datetimes[1], 'sum': sum}

        return render(request, 'report/shift.html', context)
    else:
        return render(request, 'report/shift_index.html')

slacker/backend/templates/rooms/detail.html
{% extends 'base.html' %}

{% block title %}Управление номерным фондом{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h1 class="title">
                    Комната {{ room.name }}
                </h1>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-half">
                <div class="box">
                    <div class="columns is-multiline">
                        <div class="column">
                            <div class="field">
                                <label class="label">Категория</label>
                                <span class="input is-static">{{ room.room_type }}</span>
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label class="label">Конфигурация</label>
                                <span class="input is-static">{{ room.bedding_configuration }}</span>
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label class="label">Статус</label>
                                <form action="{% url 'room-status-update' room.id %}?next={{request.path}}"
                                    method="POST">
                                    {% csrf_token %}
                                    <input type="text" value="{{ room.id }}" name="room_id" hidden>
                                    <div class="select is-rounded">
                                        <select class="select" name="status" id="id_status"
                                            onchange="this.form.submit()">
                                            <option value="EPT" {% if room.status == 'EPT' %}selected{% endif %}>Пусто
                                            </option>
                                            <option value="OCP" {% if room.status == 'OCP' %}selected{% endif %}>Занято
                                            </option>
                                            <option value="CLN" {% if room.status == 'CLN' %}selected{% endif %}>Уборка
                                            </option>
                                            <option value="RPR" {% if room.status == 'RPR' %}selected{% endif %}>Ремонт
                                            </option>
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column is-half">
                            <label class="label">Дневная ставка</label>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-user"></i></span><span>{{ room.daily_price }}<span class="icon"><i
                                            class="fas fa-sm fa-ruble-sign"></i></span></span></span>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-user-friends"></i></span><span>{{ room.daily_price_two_persons }}</span><span
                                    class="icon"><i class="fas fa-sm fa-ruble-sign"></i></span></span>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-users"></i></span><span>{{ room.daily_price_three_persons }}</span><span
                                    class="icon"><i class="fas fa-sm fa-ruble-sign"></i></span></span>
                        </div>
                        <div class="column is-half">
                            <label class="label">Почасовая ставка</label>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-user"></i></span><span>{{ room.hourly_price }}<span
                                        class="icon"><i class="fas fa-sm fa-ruble-sign"></i></span></span></span>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-user-friends"></i></span><span>{{ room.hourly_price }}</span><span
                                    class="icon"><i class="fas fa-sm fa-ruble-sign"></i></span></span>
                            <span class="input is-static"><span class="icon"><i
                                        class="fas fa-users"></i></span><span>{{ room.hourly_price_three_persons }}</span><span
                                    class="icon"><i class="fas fa-sm fa-ruble-sign"></i></span></span>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h2 class="subtitle">Заметки</h2>
                    <form action="{% url 'post-room-note' room.id %}?next={{request.path}}" method="POST">
                        {% csrf_token %}
                        <input type="text" value="{{ room.id }}" name="room_id" hidden>
                        <div class="field">
                            <textarea class="textarea" rows="3" name="content"></textarea>
                        </div>
                        <div class="field is-grouped is-grouped-right">
                            <div class="control">
                                <button class="button is-rounded is-warning">Добавить</button>
                            </div>
                        </div>
                    </form>
                    <div style="max-height: 500px; overflow: scroll; padding: 10px;">
                        {% for note in notes %}
                        <div class="box">
                            <article class="media">
                                <div class="media-content">
                                    <div class="content">
                                        <p>
                                            <strong>{{ note.created_by.first_name }}
                                                {{ note.created_by.last_name }}</strong>
                                            <small>@{{ note.created_by.username }}</small>
                                            <small>{{ note.created_at|date }} в {{ note.created_at|time }}</small>
                                            <br>
                                            {{ note.content }}
                                        </p>
                                    </div>
                                </div>
                            </article>
                        </div>
                        {% empty %}
                        <div class="box">
                            Нет записей
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <nav class="panel">
                    <p class="panel-heading">Недавние проживания</p>
                    <div style="max-height: 400px; overflow: scroll;">
                        {% for accommodation in recent_accommodations %}
                        <a href="{{ accommodation.get_absolute_url }}" class="panel-block" style="display: block">
                            <div class="level">
                                <div class="level-left">
                                    <span class="panel-icon">
                                        <i class="fas fa-clock"></i>
                                    </span>
                                    <span><strong>{{ accommodation.check_in|date:"j E 'y" }}</strong> {{ accommodation.check_in|date:"H:i" }} - <strong>{{ accommodation.check_out|date:"j E 'y" }}</strong> {{ accommodation.check_out|date:"H:i" }}</span>
                                </div>
                                <div class="level-right">
                                    {{ accommodation.cost }}
                                    <span class="panel-icon">
                                        <i class="fas fa-ruble-sign" aria-hidden="true"></i>
                                    </span>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
</section>
{% endblock %}